Google Summer of Code
tensorflow/similarity pull request #286
Opened 2022-09-12 09:14 UTC by abhisharsinha

This work was part of my Google Summer of Code project. The following are the major contributions of the project.

- Addition of multiple negatives ranking loss
- Addition of an example notebook for fine-tuning CLIP using multiple negatives ranking loss

2022-09-22 06:37 UTC, owenvallis commented
Thanks for the PR! I'll review the notebook soon and I left a few comments on the loss.

2022-10-03 00:17 UTC, owenvallis commented
@abhisharsinha, let me know your thoughts on the PR comments and we can get this merged into the dev branch.

2022-10-11 10:32 UTC, abhisharsinha commented on tensorflow_similarity/losses/multinegrank_loss.py
> +        pairwise_sim = -pairwise_sim
I agree negative distance is not an appropriate transformation for similarity in all cases. For now, I'll enforce inner_product.

2022-10-15 05:26 UTC, owenvallis requested changes

2022-10-16 09:29 UTC, abhisharsinha commented on tensorflow_similarity/losses/multinegrank_loss.py
> +    expd = tf.math.exp(pairwise_sim)
Thanks, I'll incorporate this and push the changes

2022-10-21 04:25 UTC, owenvallis commented
Meant to revert the changes to `pyproject.toml` but deleted the file. Can you please add it back with the following

```
[tool.isort]
profile = "black"

[tool.black]
 line-length = 119
```

2022-10-21 05:03 UTC, owenvallis approved these changes

2022-10-23 04:49 UTC, owenvallis approved these changes

2022-10-23 04:50 UTC, owenvallis commented
Looks like the Black and Isort formatting checks are failing for tensorflow_similarity/losses/multinegrank_loss.py. Otherwise looks good to go, thanks.

2022-10-23 04:52 UTC, owenvallis commented on examples/multimodal_example.ipynb
> +        "!pip install git+https://github.com/abhisharsinha/similarity@gsoc"
We'll want to update this once we merge into to the dev branch.

2022-10-23 22:17 UTC, owenvallis approved these changes

2022-10-23 22:18 UTC, merged