Lifted structure loss
tensorflow/similarity pull request #342
Opened 2023-07-29 11:25 UTC by Lorenzobattistela

This PR refers to Issue #102 and it is implementing the LSL described in the article https://arxiv.org/pdf/1511.06452.pdf

2023-07-29 11:32 UTC, Lorenzobattistela commented
@owenvallis fixed the CLA problem, same changes from before.

2023-07-30 01:46 UTC, owenvallis requested changes

2023-07-30 01:46 UTC, owenvallis commented on tensorflow_similarity/losses/lifted_structure_loss.py
> +        distance: Distance = "cosine",
This should be: `distance: Distance | str = "distance"`

You also need to add `from __future__ import annotations` to support the new typing syntax

2023-07-30 01:46 UTC, owenvallis commented on tensorflow_similarity/losses/lifted_structure_loss.py
> +    loss = j_values / 2.0
Seems like mypy isn't sure this is a float tensor. I think we can do the following to force the typing.

`loss: FloatTensor = j_values / 2.0`

2023-07-30 18:12 UTC, owenvallis commented
Looks like the tests/losses/test_lifted_structure_loss.py just needs to be formatted and then the PR should be good to go.

2023-08-04 11:45 UTC, Lorenzobattistela commented
@owenvallis Sorry took so long, I missed your comment in the notifications. I ran black `black . --verbose --check` in my branch locally, and i got this output:
`Oh no! 💥 💔 💥 14 files would be reformatted, 144 files would be left unchanged.`

But i commited only the change in test_lsl, since it was the file related to this PR. If it is needed to change other things, just tag me and I'll do it. Thanks!

2023-08-08 19:16 UTC, owenvallis commented
Looks like there are some isort errors with the import formatting but that shouldn't block us here. I'll format the imports on my side. 

Thanks again for implementing the loss!

2023-08-08 19:17 UTC, merged

2023-08-08 19:37 UTC, Lorenzobattistela commented
Appreciate all the help, I'll keep contributing to similarity. Thanks